### ISSUE TITLE
ArgumentError not raised when Array arg is missing

### ISSUE THREAD

**Issue by txjenniek** [leejarvis/slop#236]
Documentation seems to indicate that an ArgumentError should be thrown if you use an array type option without an argument.

```
o.array   #=> Slop::ArrayOption, expects an argument

An option used without an argument when it expects one: Slop::MissingArgument
```

However, this example code shows this is not the case.

```ruby
require 'slop'
require 'pp'

opts = Slop.parse do |o| 
    o.array '-a', '--array', "Test array"
    o.int '-i', '--integer', "Test integer"
    o.string '-s', '--string', "Test string"
end

print "Array: "
pp opts[:array]

print "Integer: "
pp opts[:integer]

print "String: "
pp opts[:string]
```

```
[~ 10:03 AM]$ ruby bug-example.rb -i
/Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/option.rb:56:in `ensure_call': missing argument for -i, --integer (Slop::MissingArgument)
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:111:in `process'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:118:in `try_process'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:60:in `block in parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `each_with_index'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/options.rb:72:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop.rb:23:in `parse'
	from bug-example.rb:4:in `<main>'
[~ 10:03 AM]$ ruby bug-example.rb -s
/Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/option.rb:56:in `ensure_call': missing argument for -s, --string (Slop::MissingArgument)
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:111:in `process'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:118:in `try_process'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:60:in `block in parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `each_with_index'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/parser.rb:49:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop/options.rb:72:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/slop-4.6.2/lib/slop.rb:23:in `parse'
	from bug-example.rb:4:in `<main>'
[~ 10:03 AM]$ ruby bug-example.rb -a
Array: []
Integer: nil
String: nil
```

It looks like the array option initializes to an empty array, and therefore fails the nil check in [option.rb](https://github.com/leejarvis/slop/blob/50ac7fb6be8d2e32ea3b62c801201a9b570c995b/lib/slop/option.rb#L52): 
```ruby
if value.nil? && expects_argument?
```

**Comment by leejarvis** [comment]
Thanks for the great bug report! 

I've spent a bit of time thinking about this. I think I could just remove [this code](https://github.com/leejarvis/slop/blob/50ac7fb6be8d2e32ea3b62c801201a9b570c995b/lib/slop/option.rb#L53-L54), which would avoid setting the default value when a flag is used without any argument. However, perhaps there's an argument for supporting `--flag` where the flag expects an argument, allowing it to behave like optparse does:

```ruby
OptionParser.new do |o|
  o.on("--list [x,y,z]") do |items|
    puts "items: #{items.inspect}"
  end
end.parse!

# ruby run.rb --list
#=> items: nil
```

Not really sure why anyone would want that, but if the code above is removed from Slop, then it's straight up no longer possible to provide a flag without any argument where a default is provided. It would be a breaking change, so I'd bump the version. 

What do you think?
